env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:import/recommended
  - plugin:import/typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
ignorePatterns:
  ["**/dist/**"]
rules:
  no-console: 'off'
  import/extensions: [1,'never']
#  linebreak-style:  ['error', process.platform === 'win32' ? 'windows' : 'unix']
  linebreak-style: 0